# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
